package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChucvuAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChucvuAllPropertiesEquals(Chucvu expected, Chucvu actual) {
        assertChucvuAutoGeneratedPropertiesEquals(expected, actual);
        assertChucvuAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChucvuAllUpdatablePropertiesEquals(Chucvu expected, Chucvu actual) {
        assertChucvuUpdatableFieldsEquals(expected, actual);
        assertChucvuUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChucvuAutoGeneratedPropertiesEquals(Chucvu expected, Chucvu actual) {
        assertThat(expected)
            .as("Verify Chucvu auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChucvuUpdatableFieldsEquals(Chucvu expected, Chucvu actual) {
        assertThat(expected)
            .as("Verify Chucvu relevant properties")
            .satisfies(e -> assertThat(e.getMacv()).as("check macv").isEqualTo(actual.getMacv()))
            .satisfies(e -> assertThat(e.getTencv()).as("check tencv").isEqualTo(actual.getTencv()))
            .satisfies(e -> assertThat(e.getHcpccv()).as("check hcpccv").isEqualTo(actual.getHcpccv()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChucvuUpdatableRelationshipsEquals(Chucvu expected, Chucvu actual) {}
}
