package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PhongbanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhongbanAllPropertiesEquals(Phongban expected, Phongban actual) {
        assertPhongbanAutoGeneratedPropertiesEquals(expected, actual);
        assertPhongbanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhongbanAllUpdatablePropertiesEquals(Phongban expected, Phongban actual) {
        assertPhongbanUpdatableFieldsEquals(expected, actual);
        assertPhongbanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhongbanAutoGeneratedPropertiesEquals(Phongban expected, Phongban actual) {
        assertThat(expected)
            .as("Verify Phongban auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhongbanUpdatableFieldsEquals(Phongban expected, Phongban actual) {
        assertThat(expected)
            .as("Verify Phongban relevant properties")
            .satisfies(e -> assertThat(e.getMapb()).as("check mapb").isEqualTo(actual.getMapb()))
            .satisfies(e -> assertThat(e.getTenpb()).as("check tenpb").isEqualTo(actual.getTenpb()))
            .satisfies(e -> assertThat(e.getSdt()).as("check sdt").isEqualTo(actual.getSdt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhongbanUpdatableRelationshipsEquals(Phongban expected, Phongban actual) {}
}
