package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TanggiamtlAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTanggiamtlAllPropertiesEquals(Tanggiamtl expected, Tanggiamtl actual) {
        assertTanggiamtlAutoGeneratedPropertiesEquals(expected, actual);
        assertTanggiamtlAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTanggiamtlAllUpdatablePropertiesEquals(Tanggiamtl expected, Tanggiamtl actual) {
        assertTanggiamtlUpdatableFieldsEquals(expected, actual);
        assertTanggiamtlUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTanggiamtlAutoGeneratedPropertiesEquals(Tanggiamtl expected, Tanggiamtl actual) {
        assertThat(expected)
            .as("Verify Tanggiamtl auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTanggiamtlUpdatableFieldsEquals(Tanggiamtl expected, Tanggiamtl actual) {
        assertThat(expected)
            .as("Verify Tanggiamtl relevant properties")
            .satisfies(e -> assertThat(e.getNgaythang()).as("check ngaythang").isEqualTo(actual.getNgaythang()))
            .satisfies(e -> assertThat(e.getTkn()).as("check tkn").isEqualTo(actual.getTkn()))
            .satisfies(e -> assertThat(e.getTkc()).as("check tkc").isEqualTo(actual.getTkc()))
            .satisfies(e -> assertThat(e.getSotien()).as("check sotien").isEqualTo(actual.getSotien()))
            .satisfies(e -> assertThat(e.getDiengiai()).as("check diengiai").isEqualTo(actual.getDiengiai()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTanggiamtlUpdatableRelationshipsEquals(Tanggiamtl expected, Tanggiamtl actual) {
        assertThat(expected)
            .as("Verify Tanggiamtl relationships")
            .satisfies(e -> assertThat(e.getNhanvien()).as("check nhanvien").isEqualTo(actual.getNhanvien()));
    }
}
